[package]
name = "socool_parser"
version = "0.1.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
edition = "2018"
#build = "build.rs" # LALRPOP preprocessing

#[build-dependencies]
#lalrpop = "0.16.0"

[dependencies]
lalrpop-util = "0.16.0"
regex = "0.2.1"
colored = "1.6"
num-rational = "0.2"

